Repository thunderbird/appointment, pull requests merged in 2024-05, with the labels that each got.

#393 Allow a user to disconnect their google account
  backend/src/appointment/database/repo/calendar.py
  backend/src/appointment/dependencies/google.py
  backend/src/appointment/routes/google.py
  frontend/src/components/SettingsAccount.vue
  frontend/src/components/SettingsCalendar.vue
  frontend/src/components/SettingsConnections.vue
  frontend/src/components/SettingsGeneral.vue
  frontend/src/definitions.js
  frontend/src/elements/SecondaryButton.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/stores/external-connections-store.js
  frontend/src/views/SettingsView.vue
Labels: l10n update

#419 fixed incorrect environment references in production workflow
  .github/workflows/deploy-production.yml
Labels: bug

#421 corrected db protection for production
  tofu/modules/data-store/database/main.tf
Labels: bug

#420 IaC documentation update
  tofu/README.md
Labels: documentation

#427 Features/397 invite codes
  backend/src/appointment/routes/auth.py
  backend/src/appointment/routes/invite.py
  backend/test/conftest.py
  backend/test/factory/invite_factory.py
  backend/test/integration/test_auth.py
  frontend/src/components/DataTable.vue
  frontend/src/definitions.js
  frontend/src/elements/ListPagination.vue
  frontend/src/elements/admin/AdminNav.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/router.js
  frontend/src/views/LoginView.vue
  frontend/src/views/admin/InviteCodePanelView.vue
  frontend/src/views/admin/SubscriberPanelView.vue
Labels: l10n update

#440 Add a preferred email option in account settings (Fixes #408)
  backend/src/appointment/controller/calendar.py
  backend/src/appointment/database/models.py
  backend/src/appointment/database/repo/subscriber.py
  backend/src/appointment/database/schemas.py
  backend/src/appointment/migrations/versions/2024_05_28_1745-9fe08ba6f2ed_update_subscribers_add_.py
  backend/src/appointment/routes/account.py
  backend/src/appointment/routes/api.py
  backend/src/appointment/routes/auth.py
  backend/src/appointment/routes/google.py
  backend/src/appointment/routes/schedule.py
  backend/test/integration/test_auth.py
  backend/test/integration/test_profile.py
  frontend/src/components/BookingModal.vue
  frontend/src/components/SettingsAccount.vue
  frontend/src/components/SettingsConnections.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/stores/user-store.js
Labels: l10n update
