Repository thunderbird/appointment, pull requests merged in 2025-02, with the labels that each got.

#846 Fix production sanity test end-of-month issues
  test/e2e/const/constants.ts
  test/e2e/pages/dashboard-page.ts
  test/e2e/playwright.config.ts
  test/e2e/tests/book-appointment.spec.ts
Labels: bug, testing

#852 Remove references to prod in env var names
  .github/workflows/deploy-production.yml
  .github/workflows/nightly-tests.yml
  test/e2e/.env.prod.example
  test/e2e/README.md
  test/e2e/const/constants.ts
  test/e2e/pages/booking-page.ts
  test/e2e/pages/fxa-page.ts
  test/e2e/pages/splashscreen-page.ts
  test/e2e/utils/utils.ts
Labels: testing

#873 Add Zendesk Link
  backend/src/appointment/controller/mailer.py
  backend/src/appointment/templates/email/includes/base.jinja2
  frontend/.env.example
  frontend/.env.prod.example
  frontend/.env.stage.example
  frontend/src/components/ExternalRedirect.vue
  frontend/src/components/NavBar.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/views/ContactView.vue
  frontend/src/views/ReportBugView.vue
Labels: l10n update

#890 Update the download data readme and make filenames consistent
  backend/src/appointment/controller/data.py
  backend/src/appointment/l10n/de/main.ftl
  backend/src/appointment/l10n/en/main.ftl
Labels: bug, l10n update
